title: Research merge — services
actions:
  - type: service.set
    id: 'exo-svc-merge-1'
    service: 'CscService'
    start: '4'
    stop: true
    whenOption: serviceStrip
    description: 'Exo'

  - type: service.set
    id: 'exo-svc-merge-2'
    service: 'StorSvc'
    start: '3'
    stop: true
    whenOption: serviceStrip
    description: 'Exo'

