<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Company>Exo</Company>
    <Authors>Exo</Authors>
    <Product>ExoOS</Product>
    <Copyright>Copyright (c) Exo</Copyright>
    <Version>1.8.1</Version>
    <RepositoryUrl>https://github.com/ImAvgErix/ExoOS</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
